Algoritmo "Cadastro_Usuario"

Var
   num1: Caractere
   num2: Caractere
   num3: Real

Inicio
   Escreva ("Digite seu nome:")
   Leia (num1)

   Escreva ("Digite sua senha:")
   Leia (num2)

   Escreva ("Digite sua idade:")
   Leia (num3)

   LimpaTela

   EscrevaL("Cadastro realizado com sucesso!")
   EscrevaL ("Nome: ", num1)
   EscrevaL ("Senha: ", num2)
   Escreva ("Idade: ", num3)

FimAlgoritmo
